0: 0_tutorial.cpp
	g++ 0_tutorial.cpp -lncurses -o 0.out
1: 1_tutorial.cpp
	g++ 1_tutorial.cpp -lncurses -o 1.out
2: 2_tutorial.cpp
	g++ 2_tutorial.cpp -lncurses -o 2.out
3: 3_tutorial.cpp
	g++ 3_tutorial.cpp -lncurses -o 3.out
4: 4_tutorial.cpp
	g++ 4_tutorial.cpp -lncurses -o 4.out

clean:
	rm ./*.out

